-- Flyway Migration: Create MFA TOTP secrets table
-- Description: Stores encrypted TOTP secrets and enrollment state for multi-factor authentication
-- Version: V300
-- Note: This migration assumes the database tablespace has encryption enabled (Oracle TDE)
-- or the application will perform AES-256-GCM encryption before storing.

CREATE TABLE MFA_TOTP_SECRETS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
    secret RAW(256) NOT NULL,  -- Encrypted TOTP secret (AES-256-GCM ciphertext + tag)
    iv RAW(16),  -- Initialization vector for encryption (if using application-level crypto)
    is_verified NUMBER(1) DEFAULT 0 CHECK (is_verified IN (0, 1)),  -- 0 = pending confirmation, 1 = active
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    verified_at TIMESTAMP,
    failed_attempts NUMBER DEFAULT 0,
    last_attempt_at TIMESTAMP,
    UNIQUE (user_id)  -- Only one TOTP secret per user
);

-- Low-cardinality is_verified index intentionally omitted; monitor query plans before adding secondary indexes.
-- Composite index for common MFA verification patterns (queries filtering by both user_id and is_verified)
CREATE INDEX idx_mfa_totp_user_verified ON MFA_TOTP_SECRETS(user_id, is_verified);

-- Audit comment for DDL tracking
COMMENT ON TABLE MFA_TOTP_SECRETS IS 'Stores encrypted TOTP (Time-based One-Time Password) secrets for MFA enrollment. Encryption: Oracle TDE at tablespace level or AES-256-GCM at application level.';
COMMENT ON COLUMN MFA_TOTP_SECRETS.secret IS 'Encrypted TOTP secret (RFC 6238). RAW(256) stores AES-256-GCM ciphertext + 16-byte tag via Oracle TDE or application-level encryption.';
COMMENT ON COLUMN MFA_TOTP_SECRETS.iv IS 'Initialization vector for application-level encryption (if using AES-256-GCM instead of TDE).';
COMMENT ON COLUMN MFA_TOTP_SECRETS.is_verified IS 'Enrollment status: 0=pending verification, 1=confirmed and active.';
COMMENT ON COLUMN MFA_TOTP_SECRETS.failed_attempts IS 'Failed verification attempts (reset after successful verification).';

