-- Flyway Migration: Create WebAuthn credentials table
-- Description: Stores FIDO2 security key registrations
-- Version: V302

CREATE TABLE MFA_WEBAUTHN_CREDENTIALS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(36) NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
    credential_id VARCHAR2(1364) NOT NULL,  -- Base64-encoded credential ID (up to 1024 bytes raw, ~1364 base64)
    public_key CLOB NOT NULL,  -- Base64-encoded public key
    nickname VARCHAR2(100),  -- User-friendly name (e.g., "YubiKey 5C"), optional per org policy
    sign_count NUMBER DEFAULT 0 CONSTRAINT chk_mfa_webauthn_sign_count_gte_0 CHECK (sign_count >= 0),  -- Signature counter for clone detection, must be non-negative
    transports VARCHAR2(100),  -- Comma-separated transports (usb, ble, nfc, internal)
    attestation_format VARCHAR2(20),  -- Attestation format (fido-u2f, packed, tpm, android-key, etc.)
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    last_used_at TIMESTAMP,
    UNIQUE (user_id, credential_id)  -- User + credential uniqueness
);

CREATE INDEX idx_mfa_webauthn_user_id ON MFA_WEBAUTHN_CREDENTIALS(user_id);
CREATE INDEX idx_mfa_webauthn_cred_id ON MFA_WEBAUTHN_CREDENTIALS(credential_id);
CREATE INDEX idx_mfa_webauthn_last_used ON MFA_WEBAUTHN_CREDENTIALS(last_used_at);

COMMENT ON TABLE MFA_WEBAUTHN_CREDENTIALS IS 'Stores WebAuthn (FIDO2) security key credentials for user authentication.';
COMMENT ON COLUMN MFA_WEBAUTHN_CREDENTIALS.credential_id IS 'Unique identifier for the credential (up to 1364 chars for Base64-encoded 1024-byte values). Optional: encrypt per org policy.';
COMMENT ON COLUMN MFA_WEBAUTHN_CREDENTIALS.public_key IS 'User public key for signature verification (CBOR encoded).';
COMMENT ON COLUMN MFA_WEBAUTHN_CREDENTIALS.sign_count IS 'Signature counter used to detect cloned authenticators.';
COMMENT ON COLUMN MFA_WEBAUTHN_CREDENTIALS.attestation_format IS 'Format of the attestation statement (for trust decisions).';

