-- Flyway Migration: Create MFA backup codes table
-- Description: Stores one-time backup codes for MFA recovery
-- Version: V303

CREATE TABLE MFA_BACKUP_CODES (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
    code RAW(256) NOT NULL,  -- AES-256-GCM ciphertext for backup code value
    is_used NUMBER(1) DEFAULT 0,  -- 0 = available, 1 = consumed
    used_at TIMESTAMP,
    used_by_admin_id NUMBER(19) REFERENCES USERS(id),  -- If admin override, who used it
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    UNIQUE (user_id, code)  -- User + code uniqueness
);

CREATE INDEX idx_mfa_backup_user_id ON MFA_BACKUP_CODES(user_id);
CREATE INDEX idx_mfa_backup_is_used ON MFA_BACKUP_CODES(is_used);
CREATE INDEX idx_mfa_backup_created ON MFA_BACKUP_CODES(created_at);

COMMENT ON TABLE MFA_BACKUP_CODES IS 'Single-use backup codes for MFA recovery if user loses primary device.';
COMMENT ON COLUMN MFA_BACKUP_CODES.code IS 'Encrypted backup code (RAW). Store AES-256-GCM ciphertext of formatted code, never plaintext.';
COMMENT ON COLUMN MFA_BACKUP_CODES.is_used IS 'Usage status: 0=available, 1=consumed (one-time use only).';
COMMENT ON COLUMN MFA_BACKUP_CODES.used_by_admin_id IS 'If admin override used this code, reference to admin user.';

