-- Flyway Migration: Create MFA backup codes table
-- Description: Stores one-time backup codes for MFA recovery
-- Version: V303

CREATE TABLE MFA_BACKUP_CODES (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,  -- User identifier (numeric FK to users.id)
    code_hash VARCHAR2(255) NOT NULL,  -- BCrypt hash of backup code
    used_at TIMESTAMP,  -- NULL = available, timestamp = consumed
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_mfa_backup_code UNIQUE (user_id, code_hash),  -- User + hash uniqueness
    CONSTRAINT fk_mfa_backup_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_mfa_backup_user_id ON MFA_BACKUP_CODES(user_id);
CREATE INDEX idx_mfa_backup_used_at ON MFA_BACKUP_CODES(used_at);
CREATE INDEX idx_mfa_backup_created ON MFA_BACKUP_CODES(created_at);

COMMENT ON TABLE MFA_BACKUP_CODES IS 'Single-use backup codes for MFA recovery if user loses primary device.';
COMMENT ON COLUMN MFA_BACKUP_CODES.code_hash IS 'BCrypt hash of backup code. Stored as salted hash, never plaintext. Use BCrypt.checkpw() to verify.';
COMMENT ON COLUMN MFA_BACKUP_CODES.used_at IS 'Consumption timestamp: NULL=available, timestamp=consumed (one-time use only).';
COMMENT ON COLUMN MFA_BACKUP_CODES.user_id IS 'User identifier who owns these backup codes.';


