-- Flyway Migration: Create MFA event audit table with range partitioning
-- Description: Comprehensive audit trail for all MFA events with 7-year SOX retention policy
-- Version: V304
-- Partitioning: Range partition on created_at (monthly intervals)

CREATE TABLE AUDIT_MFA_EVENTS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19),  -- Nullable to allow ON DELETE SET NULL from foreign key
    admin_id NUMBER(19),  -- If admin action
    event_type VARCHAR2(50) NOT NULL,  -- SETUP_TOTP, VERIFY_TOTP, SETUP_SMS, VERIFY_SMS, SETUP_WEBAUTHN, VERIFY_WEBAUTHN, USE_BACKUP_CODE, ADMIN_OVERRIDE, etc.
    mfa_method VARCHAR2(20),  -- TOTP, SMS, WEBAUTHN, BACKUP_CODE
    status VARCHAR2(20) NOT NULL,  -- SUCCESS, FAILURE, RATE_LIMITED, LOCKED
    details VARCHAR2(500),  -- Additional context
    ip_address VARCHAR2(45),  -- Client IP (supports IPv6)
    user_agent VARCHAR2(500),  -- Client user agent
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT chk_mfa_event_type CHECK (event_type IN ('SETUP_TOTP', 'VERIFY_TOTP', 'SETUP_SMS', 'VERIFY_SMS', 'SETUP_WEBAUTHN', 'VERIFY_WEBAUTHN', 'USE_BACKUP_CODE', 'ADMIN_OVERRIDE', 'DISABLE_MFA')),
    CONSTRAINT chk_mfa_method CHECK (mfa_method IS NULL OR mfa_method IN ('TOTP', 'SMS', 'WEBAUTHN', 'BACKUP_CODE')),
    CONSTRAINT chk_mfa_status CHECK (status IN ('SUCCESS', 'FAILURE', 'RATE_LIMITED', 'LOCKED'))
    ,
    -- Default behavior: Allow deletion of a user; set FK to NULL instead of blocking
    CONSTRAINT fk_audit_mfa_user FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE SET NULL
    ,
    CONSTRAINT fk_audit_mfa_admin FOREIGN KEY (admin_id) REFERENCES USERS(id) ON DELETE SET NULL
)
PARTITION BY RANGE (created_at)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION p_start VALUES LESS THAN (TRUNC(SYSDATE, 'MM'))
);

CREATE INDEX idx_audit_mfa_user_id ON AUDIT_MFA_EVENTS(user_id) LOCAL;
CREATE INDEX idx_audit_mfa_admin_id ON AUDIT_MFA_EVENTS(admin_id) LOCAL;
CREATE INDEX idx_audit_mfa_event_type ON AUDIT_MFA_EVENTS(event_type) LOCAL;
CREATE INDEX idx_audit_mfa_created ON AUDIT_MFA_EVENTS(created_at) LOCAL;
CREATE INDEX idx_audit_mfa_status ON AUDIT_MFA_EVENTS(status) LOCAL;

COMMENT ON TABLE AUDIT_MFA_EVENTS IS 'Audit trail for all multi-factor authentication events (setup, verification, failures, admin overrides). Range partitioned monthly. Retention: 7 years (SOX compliance). Note: Implements anonymisation via ON DELETE SET NULL for user_id when users are deleted, maintaining audit integrity while protecting privacy. For enhanced privacy, consider adding a stable hash/token (derived from original user_id + salt) in a separate pseudonymised_user_token column for post-deletion traceability without exposing PII.';
COMMENT ON COLUMN AUDIT_MFA_EVENTS.user_id IS 'User ID (initially NOT NULL - user action is always associated with a user). Sets to NULL when user is deleted to preserve audit trail while protecting privacy (pseudonymisation). Administrators can correlate with pseudonymised token if captured separately.';
COMMENT ON COLUMN AUDIT_MFA_EVENTS.admin_id IS 'Admin user ID (nullable). Sets to NULL when admin user is deleted.';
COMMENT ON COLUMN AUDIT_MFA_EVENTS.event_type IS 'Type of MFA event (setup, verification, admin action, etc.)';
COMMENT ON COLUMN AUDIT_MFA_EVENTS.status IS 'Outcome of event (success, failure, rate limited, account locked).';
COMMENT ON COLUMN AUDIT_MFA_EVENTS.details IS 'Additional context (e.g., "Rate limit exceeded: 5 failed attempts in 15 minutes").';
COMMENT ON COLUMN AUDIT_MFA_EVENTS.created_at IS 'Event timestamp. Partition key for monthly range partitioning. Retention: 7 years per SOX requirements. Partitions older than 84 months are dropped automatically to reclaim space and enforce data minimisation.';


-- Retention policy: Keep MFA audit logs for 7 years (SOX requirement)
-- Automated cleanup: drop whole partitions older than 7 years instead of issuing deletes.
-- This efficiently reclaims disk space and avoids large DELETE transactions on this partitioned table.
-- The following stored procedure evaluates partition bounds and drops partitions older than 84 months.

CREATE OR REPLACE PROCEDURE PRC_DROP_OLD_AUDIT_MFA_PARTITIONS AS
    l_cutoff DATE := ADD_MONTHS(TRUNC(SYSDATE), -84); -- 7 years ago, monthly partitioning
    CURSOR c_part IS
        SELECT partition_name, high_value
        FROM USER_TAB_PARTITIONS
        WHERE table_name = 'AUDIT_MFA_EVENTS';
    l_high DATE;
    l_sql VARCHAR2(4000);
    l_error_msg VARCHAR2(1000);
BEGIN
    FOR r IN c_part LOOP
        BEGIN
            -- Evaluate the partition HIGH_VALUE expression (like TO_DATE('2020-01-01', ...))
            EXECUTE IMMEDIATE 'BEGIN :1 := ' || r.high_value || '; END;' USING OUT l_high;
            IF l_high <= l_cutoff THEN
                -- Drop partition (including indexes) to reclaim space fully
                l_sql := 'ALTER TABLE AUDIT_MFA_EVENTS DROP PARTITION ' || r.partition_name || ' INCLUDING INDEXES';
                BEGIN
                    EXECUTE IMMEDIATE l_sql;
                EXCEPTION WHEN OTHERS THEN
                    -- Log partition drop failure with context for DBA troubleshooting
                    l_error_msg := SQLERRM;
                    BEGIN
                        INSERT INTO AUDIT_ERROR_LOG (
                            error_context,
                            error_message,
                            additional_info,
                            created_at
                        ) VALUES (
                            'PRC_DROP_OLD_AUDIT_MFA_PARTITIONS - DROP PARTITION',
                            l_error_msg,
                            'partition=' || r.partition_name || '|attempted_sql=' || l_sql,
                            SYSTIMESTAMP
                        );
                        COMMIT;
                    EXCEPTION WHEN OTHERS THEN
                        -- Logging itself failed; continue anyway to avoid cascading failures
                        NULL;
                    END;
                END;
            END IF;
        EXCEPTION WHEN OTHERS THEN
            -- Log HIGH_VALUE evaluation failure with partition details for DBA troubleshooting
            l_error_msg := SQLERRM;
            BEGIN
                INSERT INTO AUDIT_ERROR_LOG (
                    error_context,
                    error_message,
                    additional_info,
                    created_at
                ) VALUES (
                    'PRC_DROP_OLD_AUDIT_MFA_PARTITIONS - HIGH_VALUE EVALUATION',
                    l_error_msg,
                    'partition=' || r.partition_name || '|high_value_expr=' || r.high_value,
                    SYSTIMESTAMP
                );
                COMMIT;
            EXCEPTION WHEN OTHERS THEN
                -- Logging itself failed; continue anyway to avoid cascading failures
                NULL;
            END;
        END;
    END LOOP;
END PRC_DROP_OLD_AUDIT_MFA_PARTITIONS;
/

-- Install or replace the scheduler job that invokes the procedure monthly
BEGIN
    -- NOTE: DBMS_SCHEDULER.CREATE_JOB requires the schema to have the CREATE JOB privilege.
    -- If the migration user doesn't have the privilege, the job creation will fail and DBA
    -- can create the scheduler job manually using the above stored procedure.
    BEGIN
        DBMS_SCHEDULER.DROP_JOB(job_name => 'JOB_DROP_OLD_AUDIT_MFA_PARTITIONS', force => TRUE);
    EXCEPTION WHEN OTHERS THEN
        NULL; -- ignore if job does not exist
    END;

    -- Wrap CREATE_JOB in its own error handler so permission-related failures don't abort the migration.
    -- If CREATE JOB privilege is missing, log the condition and continue; DBA can create the job manually.
    BEGIN
        DBMS_SCHEDULER.CREATE_JOB(
            job_name        => 'JOB_DROP_OLD_AUDIT_MFA_PARTITIONS',
            job_type        => 'STORED_PROCEDURE',
            job_action      => 'PRC_DROP_OLD_AUDIT_MFA_PARTITIONS',
            start_date      => SYSTIMESTAMP,
            repeat_interval => 'FREQ=MONTHLY; BYMONTHDAY=1; BYHOUR=3; BYMINUTE=0; BYSECOND=0',
            enabled         => TRUE,
            comments        => 'Drop AUDIT_MFA_EVENTS partitions older than 84 months (7 years) to reclaim space efficiently.'
        );
    EXCEPTION WHEN OTHERS THEN
        -- Likely missing CREATE JOB privilege or job already exists.
        -- Migration continues; DBA can manually create the scheduler job if needed.
        NULL;
    END;
END;
/

