-- Flyway Migration: Create MFA event audit table with range partitioning
-- Description: Comprehensive audit trail for all MFA events with 7-year SOX retention policy
-- Version: V304
-- Partitioning: Range partition on created_at (monthly intervals)

CREATE TABLE AUDIT_MFA_EVENTS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES USERS(id),
    admin_id NUMBER REFERENCES USERS(id),  -- If admin action
    event_type VARCHAR2(50) NOT NULL,  -- SETUP_TOTP, VERIFY_TOTP, SETUP_SMS, VERIFY_SMS, SETUP_WEBAUTHN, VERIFY_WEBAUTHN, USE_BACKUP_CODE, ADMIN_OVERRIDE, etc.
    mfa_method VARCHAR2(20),  -- TOTP, SMS, WEBAUTHN, BACKUP_CODE
    status VARCHAR2(20),  -- SUCCESS, FAILURE, RATE_LIMITED, LOCKED
    details VARCHAR2(500),  -- Additional context
    ip_address VARCHAR2(45),  -- Client IP (supports IPv6)
    user_agent VARCHAR2(500),  -- Client user agent
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT chk_mfa_event_type CHECK (event_type IN ('SETUP_TOTP', 'VERIFY_TOTP', 'SETUP_SMS', 'VERIFY_SMS', 'SETUP_WEBAUTHN', 'VERIFY_WEBAUTHN', 'USE_BACKUP_CODE', 'ADMIN_OVERRIDE', 'DISABLE_MFA')),
    CONSTRAINT chk_mfa_method CHECK (mfa_method IS NULL OR mfa_method IN ('TOTP', 'SMS', 'WEBAUTHN', 'BACKUP_CODE')),
    CONSTRAINT chk_mfa_status CHECK (status IN ('SUCCESS', 'FAILURE', 'RATE_LIMITED', 'LOCKED'))
)
PARTITION BY RANGE (created_at)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION p_start VALUES LESS THAN (TRUNC(SYSDATE, 'MM'))
);

CREATE INDEX idx_audit_mfa_user_id ON AUDIT_MFA_EVENTS(user_id) LOCAL;
CREATE INDEX idx_audit_mfa_admin_id ON AUDIT_MFA_EVENTS(admin_id) LOCAL;
CREATE INDEX idx_audit_mfa_event_type ON AUDIT_MFA_EVENTS(event_type) LOCAL;
CREATE INDEX idx_audit_mfa_created ON AUDIT_MFA_EVENTS(created_at) LOCAL;
CREATE INDEX idx_audit_mfa_status ON AUDIT_MFA_EVENTS(status) LOCAL;

COMMENT ON TABLE AUDIT_MFA_EVENTS IS 'Audit trail for all multi-factor authentication events (setup, verification, failures, admin overrides). Range partitioned monthly. Retention: 7 years (SOX compliance).';
COMMENT ON COLUMN AUDIT_MFA_EVENTS.user_id IS 'User ID (NOT NULL - user action is always associated with a user).';
COMMENT ON COLUMN AUDIT_MFA_EVENTS.event_type IS 'Type of MFA event (setup, verification, admin action, etc.)';
COMMENT ON COLUMN AUDIT_MFA_EVENTS.status IS 'Outcome of event (success, failure, rate limited, account locked).';
COMMENT ON COLUMN AUDIT_MFA_EVENTS.details IS 'Additional context (e.g., "Rate limit exceeded: 5 failed attempts in 15 minutes").';
COMMENT ON COLUMN AUDIT_MFA_EVENTS.created_at IS 'Event timestamp. Partition key for monthly range partitioning.';

-- Retention policy: Keep MFA audit logs for 7 years (SOX requirement)
-- Automated cleanup job will run: DELETE FROM AUDIT_MFA_EVENTS WHERE created_at < ADD_MONTHS(TRUNC(SYSDATE), -84);

