CREATE SEQUENCE audit_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE audit_dynamic_crud (
    id NUMBER PRIMARY KEY,
    table_name VARCHAR2(128) NOT NULL,
    operation VARCHAR2(10) NOT NULL,
    actor VARCHAR2(128),
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
)
ROW STORE COMPRESS ADVANCED
PARTITION BY RANGE (created_at)
(
    PARTITION P_2024_10 VALUES LESS THAN (TO_DATE('2024-11-01','YYYY-MM-DD')),
    PARTITION P_2024_11 VALUES LESS THAN (TO_DATE('2024-12-01','YYYY-MM-DD')),
    PARTITION P_9999_12 VALUES LESS THAN (TO_DATE('9999-12-31','YYYY-MM-DD'))
);

CREATE TABLE audit_login_attempts (
    id NUMBER PRIMARY KEY,
    username VARCHAR2(255) NOT NULL,
    success NUMBER(1) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
)
ROW STORE COMPRESS ADVANCED
PARTITION BY RANGE (created_at)
(
    PARTITION P_2024_10 VALUES LESS THAN (TO_DATE('2024-11-01','YYYY-MM-DD')),
    PARTITION P_2024_11 VALUES LESS THAN (TO_DATE('2024-12-01','YYYY-MM-DD')),
    PARTITION P_9999_12 VALUES LESS THAN (TO_DATE('9999-12-31','YYYY-MM-DD'))
);

CREATE TABLE audit_sessions (
    id NUMBER PRIMARY KEY,
    user_id VARCHAR2(36),
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
)
ROW STORE COMPRESS ADVANCED
PARTITION BY RANGE (created_at)
(
    PARTITION P_2024_10 VALUES LESS THAN (TO_DATE('2024-11-01','YYYY-MM-DD')),
    PARTITION P_2024_11 VALUES LESS THAN (TO_DATE('2024-12-01','YYYY-MM-DD')),
    PARTITION P_9999_12 VALUES LESS THAN (TO_DATE('9999-12-31','YYYY-MM-DD'))
);

CREATE TABLE audit_error_log (
    id NUMBER PRIMARY KEY,
    error_code VARCHAR2(50),
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
)
ROW STORE COMPRESS ADVANCED
PARTITION BY RANGE (created_at)
(
    PARTITION P_2024_10 VALUES LESS THAN (TO_DATE('2024-11-01','YYYY-MM-DD')),
    PARTITION P_2024_11 VALUES LESS THAN (TO_DATE('2024-12-01','YYYY-MM-DD')),
    PARTITION P_9999_12 VALUES LESS THAN (TO_DATE('9999-12-31','YYYY-MM-DD'))
);

INSERT INTO audit_dynamic_crud (id, table_name, operation, actor, created_at)
SELECT audit_seq.NEXTVAL,
       'USERS',
       CASE WHEN MOD(level, 2) = 0 THEN 'INSERT' ELSE 'UPDATE' END,
       'svc-user',
       ADD_MONTHS(TRUNC(SYSTIMESTAMP, 'MM'), -MOD(level, 6))
  FROM dual CONNECT BY level <= 100;

INSERT INTO audit_login_attempts (id, username, success, created_at)
SELECT audit_seq.NEXTVAL,
       'user' || TO_CHAR(level),
       MOD(level, 2),
       ADD_MONTHS(TRUNC(SYSTIMESTAMP, 'MM'), -MOD(level, 6))
  FROM dual CONNECT BY level <= 100;

INSERT INTO audit_sessions (id, user_id, created_at)
SELECT audit_seq.NEXTVAL,
       'usr-' || level,
       ADD_MONTHS(TRUNC(SYSTIMESTAMP, 'MM'), -MOD(level, 6))
  FROM dual CONNECT BY level <= 100;

INSERT INTO audit_error_log (id, error_code, created_at)
SELECT audit_seq.NEXTVAL,
       'ERR-' || MOD(level, 10),
       ADD_MONTHS(TRUNC(SYSTIMESTAMP, 'MM'), -MOD(level, 6))
  FROM dual CONNECT BY level <= 100;

COMMIT;
